version: '3'

services:

  broker-service:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80" #port 8080 on the localhost maps to port 80 on the container
    deploy:
      mode: replicated
      replicas: 1